### ISSUE TITLE
Versions and build tools

### ISSUE THREAD

**Issue by oleks** [diku-dk/ap-e2024-pub#2]
Can you clarify which version of Haskell and (maybe) Erlang, as well which build tools (e.g., [cabal-install](https://cabal.readthedocs.io/en/stable/) or [Stack](https://docs.haskellstack.org/en/stable/)) will be used.

It can be a good idea to install the right tools ahead of time.

**Comment by athas** [comment]
https://github.com/diku-dk/ap-e2024-pub/blob/main/haskell.md
